spring.application.name=MovieReviews

spring.datasource.url=jdbc:postgresql://localhost:5432/chdb
spring.datasource.username=postgres
spring.datasource.password=1605
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect